title: "Career Development Curriculum - Turing School of Software and Design"
description: "Open source career development curriculum for the Turing School of Software and Design"
url: "https://careerdev.turing.io/"

baseurl: '/'
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

gems:
  - jemoji
