title: "Career Development Curriculum - Turing School of Software and Design"
description: "Open source career development curriculum for the Turing School of Software and Design"
url: "https://career.turing.io/"

baseurl: '/career-development-curriculum-site/'
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/career-development-curriculum-site/assets'

images:
  root_url: '/career-development-curriculum-site/assets/images'

gems:
  - jemoji
